2025-08-21 10:33:10,734 - INFO - Starting UPT Dashboard on http://localhost:5000 - C:\Users\PX3 pro Machine\UPT\Shared\dashboard.py
2025-08-21 10:33:11,087 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.96.0.52:5000 - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-21 10:33:11,087 - INFO - [33mPress CTRL+C to quit[0m - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-21 10:38:00,691 - INFO - Starting UPT Dashboard on http://localhost:5000 - C:\Users\PX3 pro Machine\UPT\Shared\dashboard.py
2025-08-21 10:38:00,773 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.96.0.52:5000 - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-21 10:38:00,773 - INFO - [33mPress CTRL+C to quit[0m - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-22 04:54:57,375 - ERROR - Template not found: templates\dashboard.html - C:\Users\PX3 pro Machine\UPT\Shared\dashboard.py
2025-08-22 04:54:57,497 - INFO - 192.168.1.85 - - [22/Aug/2025 04:54:57] "[35m[1mGET / HTTP/1.1[0m" 500 - - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-22 04:54:58,832 - INFO - 192.168.1.85 - - [22/Aug/2025 04:54:58] "[33mGET /loginMsg.js HTTP/1.1[0m" 404 - - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
2025-08-22 04:54:58,846 - INFO - 192.168.1.85 - - [22/Aug/2025 04:54:58] "[33mGET /cgi/get.cgi?cmd=home_login HTTP/1.1[0m" 404 - - C:\Users\PX3 pro Machine\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py
